name: borniak
description: Borniak Company

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  flex_color_scheme: ^7.0.5
  cached_network_image: ^3.2.3
  feedback: ^2.6.0
  auto_route: ^7.1.0
  flutter_rating_bar: ^4.0.1
  google_nav_bar: ^5.0.6
  get: ^4.6.5
  google_maps_flutter: ^2.2.8
  ferry: ^0.14.2+1
  gql_http_link: ^1.0.0
  hive: ^2.2.3
  ferry_hive_store: ^0.5.1
  hive_flutter: ^1.1.0

dev_dependencies:
  ferry_generator: ^0.8.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
